 const countryList = [
	"Aaland Islands",
   "Afghanistan",
   "Albania",
   "American Samoa",
   "Andorra",
   "Angola",
   "Anguilla",
   "Antarctica",
	"Antigua And Barbuda",
   "Argentina",
   "Armenia",
   "Aruba",
   "Australia",
   "Austria",
   "Azerbaijan",
   "Bahamas",
   "Bahrain",
   "Bangladesh",
   "Barbados",
   "Belarus",
   "Belgium",
   "Belize'",
   "Benin",
   "Bermuda",
   "Bhutan",
   "Bolivia",
   "Bosnia And Herzegowina",
   "Botswana",
   "Bouvet Island",
   "Brazil",
   "British Indian Ocean Territory",
   "Brunei Darussalam",
   "Bulgaria",
   "Burkina Faso",
   "Burundi",
   "Cambodia",
   "Cameroon",
   "Canada",
   "Cape Verde",
   "Cayman Islands",
   "Central African Republic",
   "Chad",
   "Chile",
   "China",
   "Christmas Island",
   "Colombia",
   "Comoros",
   "Cook Islands",
   "Costa Rica",
   "Cote D'ivoire",
   "Cuba",
   "Cyprus",
   "Czech Republic",
   "Denmark",
   "Djibouti",
   "Dominica",
   "Dominican Republic",
   "Ecuador",
   "Egypt",
   "El Salvador",
   "Equatorial Guinea",
   "Eritrea",
   "Estonia",
   "Ethiopia",
   "Faroe Islands",
   "Fiji",
   "Finland",
   "France",
   "French Guiana",
   "French Polynesia",
   "French Southern Territories",
   "Gabon",
   "Gambia",
   "Georgia",
   "Germany",
   "Ghana",
   "Gibraltar",
   "Greece",
   "Greenland",
   "Grenada",
   "Guadeloupe",
   "Guam",
   "Guatemala",
   "Guinea",
   "Guinea-Bissau",
   "Guyana",
   "Haiti",
   "Heard And Mc Donald Islands",
   "Honduras",
   "Hong Kong",
   "Hungary",
   "Iceland",
   "India",
   "Indonesia",
   "Iraq",
   "Ireland",
   "Israel",
   "Italy",
   "Jamaica",
	"Japan",
   "Jordan",
   "Kazakhstan",
   "Kenya",
   "Kiribati",
   "Kuwait",
   "Kyrgyzstan",
   "Lao People's Democratic Republic",
   "Latvia",
   "Lebanon",
   "Lesotho",
   "Liberia",
   "Libyan Arab Jamahiriya",
   "Liechtenstein",
   "Lithuania",
   "Luxembourg",
   "Macau",
   "Madagascar",
   "Malawi",
   "Malaysia",
   "Maldives",
   "Mali",
   "Malta",
   "Marshall Islands",
   "Martinique",
   "Mauritania",
   "Mauritius",
   "Mayotte",
   "Mexico",
   "Monaco",
   "Mongolia",
   "Montserrat",
   "Morocco",
   "Mozambique",
   "Myanmar",
   "Namibia",
   "Nauru",
   "Nepal",
   "Netherlands",
   "Netherlands Antilles",
   "New Caledonia",
   "New Zealand",
	"Nicaragua",
   "Niger",
	"Nigeria",
   "Niue",
   "Norfolk Island",
   "Northern Mariana Islands",
   "Norway",
   "Oman",
   "Pakistan",
   "Palau",
   "Panama",
   "Papua New Guinea",
   "Paraguay",
   "Peru",
   "Philippines",
   "Pitcairn",
   "Poland",
   "Portugal",
   "Puerto Rico",
   "Qatar",
	"Reunion",
   "Romania",
   "Russian Federation",
   "Rwanda",
   "Saint Helena",
   "Saint Kitts And Nevis",
   "Saint Lucia",
   "Saint Pierre And Miquelon",
   "Saint Vincent And The Grenadines",
   "Samoa",
   "San Marino",
   "Sao Tome And Principe",
   "Saudi Arabia",
   "Senegal",
   "Serbia And Montenegro",
   "Seychelles",
   "Sierra Leone",
   "Singapore",
   "Slovakia",
	"Slovenia",
   "Solomon Islands",
   "Somalia",
   "South Africa",
   "South Georgia And The South Sandwich Islands",
   "Spain",
   "Sri Lanka",
   "Sudan",
   "Suriname",
   "Svalbard And Jan Mayen Islands",
   "Swaziland",
   "Sweden",
   "Switzerland",
   "Syrian Arab Republic",
   "Taiwan",
   "Tajikistan",
   "Thailand",
   "Timor-Leste",
   "Togo",
   "Tokelau",
   "Tonga",
   "Trinidad And Tobago",
   "Tunisia",
   "Turkey",
   "Turkmenistan",
   "Turks And Caicos Islands",
   "Tuvalu",
   "Uganda",
   "Ukraine",
   "United Arab Emirates",
   "United Kingdom",
   "United States",
   "United States Minor Outlying Islands",
   "Uruguay",
   "Uzbekistan",
   "Vanuatu",
   "Venezuela",
   "Viet Nam",
   "Wallis And Futuna Islands",
   "Western Sahara",
   "Yemen",
   "Zambia",
   "Zimbabwe",
 ];
 
 // eslint-disable-next-line no-undef
 const autoCompleteJS = new autoComplete({
	placeHolder: 'Country name...',
	data: {
		src: countryList,
		cache: true,
	},

	resultItem: {
		highlight: true,
	},

	events: {
		input: {
			selection: (event) => {
				const selection = event.detail.selection.value;
				autoCompleteJS.input.value = selection;
			},
		},
	},

	resultsList: {
		maxResults: 15,
	},

	searchEngine: 'strict', // strict | loose
 });